Update ipsec

diff --git a/strongswan_IPsec/ipsec b/strongswan_IPsec/ipsec
--- a/strongswan_IPsec/ipsec
+++ b/strongswan_IPsec/ipsec
@@ -1,8 +1,8 @@
 #! /bin/sh
 ### BEGIN INIT INFO
-# Provides:          strongswan IPsec services
-# Required-Start:    $network $local_fs
-# Required-Stop:     $network $local_fs
+# Provides:          ipsec
+# Required-Start:    $network $remote_fs
+# Required-Stop:     $network $remote_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Strongswan IPsec services
@@ -14,12 +14,13 @@
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="strongswan IPsec services"
 NAME=ipsec
-DAEMON=/usr/sbin/$NAME
-PIDFILE=/var/run/$NAME.pid
+STARTER=/usr/sbin/$NAME
+PIDFILE=/var/run/charon.pid
+CHARON=/usr/lib/ipsec/charon
 SCRIPTNAME=/etc/init.d/$NAME
 
 # Exit if the package is not installed
-[ -x "$DAEMON" ] || exit 0
+[ -x "$STARTER" ] || exit 0
 
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
@@ -31,6 +32,9 @@ SCRIPTNAME=/etc/init.d/$NAME
 # Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
 
+# Create lock dir
+mkdir -p /var/lock/subsys
+
 #
 # Function that starts the daemon/service
 #
@@ -40,10 +44,15 @@ do_start()
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+
+	# test if charon is currently running
+. /etc/ipsec.d/start-ipsec-sysctl.sh
+	if [ -e $CHARON ]; then
+	  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $CHARON --test > /dev/null \
 		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- start \
-		|| return 2
+	fi
+
+	$STARTER start || return 2
 }
 
 #
@@ -57,27 +66,38 @@ do_stop()
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
 	# give the proper signal to stop
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- stop \
-		|| return 2
+. /etc/ipsec.d/stop-ipsec-sysctl.sh
+	$STARTER stop || return 2
+
+	RETVAL=0
 	# but kill if that didn't work
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
-	RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
+	if [ -e $PIDFILE ]; then
+		start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+		RETVAL="$?"
+		[ "$RETVAL" = 2 ] && return 2
+	fi
+
 	# Wait for children to finish too if this is a daemon that forks
 	# and if the daemon is only ever run from this initscript.
 	# If the above conditions are not satisfied then add some other code
 	# that waits for the process to drop all resources that could be
 	# needed by services started subsequently.  A last resort is to
 	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
-	[ "$?" = 2 ] && return 2
-	# Many daemons don't delete their pidfiles when they exit.
+	if [ -e $CHARON ]; then
+	  start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $CHARON
+	  [ "$?" = 2 ] && return 2
+	fi
+
+	# strongswan is known to leave PID files behind when something goes wrong, cleanup here
 	rm -f $PIDFILE
+	# and just to make sure they are really really dead at this point...
+	killall -9 $CHARON 2>/dev/null
+
 	return "$RETVAL"
 }
 
 do_reload() {
-	$DAEMON reload
+	$STARTER reload
 	return 0
 }
 
@@ -99,7 +119,7 @@ case "$1" in
 	esac
 	;;
   status)
-	$DAEMON status
+	$STARTER status || exit $?
 	;;
   reload|force-reload)
 	log_daemon_msg "Reloading $DESC" "$NAME"
